#
# Module manifest for module 'NewHtmlReport'
#
# Generated by: Matt Boren
#
# Generated on: 12/6/2015
#

@{

# Script module or binary module file associated with this manifest.
ModuleToProcess = 'New-HtmlReport.psm1'

# Version number of this module.
ModuleVersion = '1.1'

# ID used to uniquely identify this module
GUID = '6d98afac-7cbb-44c2-996b-1d8aa3c61a9d'

# Author of this module
Author = 'Matt Boren, Jaron Hilger'

# Company or vendor of this module
CompanyName = 'None'

# Copyright statement for this module
Copyright = 'None'

# Description of the functionality provided by this module
Description = 'Module with function to create HTML output with nice layout/features (jQuery integration, for example)'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '2.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = ''

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess. Scripts (.ps1) that are listed in the NestedModules key are run in the module's session state
NestedModules = @('New-HtmlReport_configItems.ps1')

# Functions to export from this module
FunctionsToExport = '*'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = 'NewHtmlReport.psd1', 'New-HtmlReport.psm1',
               'New-HtmlReport_configItems.ps1'

# Private data to pass to the module specified in RootModule/ModuleToProcess
# PrivateData = ''

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


